### ISSUE TITLE
Redfish trips in fishin_CHPs

### ISSUE THREAD

**Issue by IreneAndru** [Maritimes/Mar.fleets#2]
This query:
est_4X5Y_2017<- fishin_CHPs(type="ALL", stock = "4X5Y", dateStart = "2017-01-01", dateEnd= "2017-12-31", returnISDB=FALSE, useLocal = T, data.dir='C:/LocalDataDump', usepkg="roracle", oracle.username=AwesomeUser, oracle.dsn="PTRAN", oracle.password=AwesomePwd)

Results in records like this one: LOG_EFRT_STD_INFO_ID==1282589

In the DB, #1282589 shows up as having a mesh size of 110mm, making it a redfish trip and not a CHP trip. Halp.

**Comment by MMMcMahon** [comment]
Hey - please check your version of the package
`est_4X5Y_2017$params$user[est_4X5Y_2017$params$user$PARAMETER=="Mar.fleets version","VALUE"]`
I have 2021.11.10, and I expect you have an earlier one.  With the addition of some more advanced gear specificity, fishin_CHPs() no longer allows `type="ALL"` - it must be either "MOBILE" or "FIXED".

When I run the same query (trying both MOBILE and FIXED, I do not see that set appearing anymore.  

Additionally, the gear information associated with each set (e.g. the mesh size) is now visible as part of the est_4X5Y_2017$fleet$FLEET_ACTIVITY object.

**Comment by MMMcMahon** [comment]
Also - for what you're doing, your function call doesn't need all of those parameters.  Assuming you change type from ALL to MOBILE, you could just do:
`est_4X5Y_2017<- fishin_CHPs(type="MOBILE", stock = "4X5Y", year=2017, returnISDB=FALSE, useLocal = T, data.dir='C:/LocalDataDump`)`
